# xbdm_gdb_bridge Setup Wizard
# Run this script to configure your connection to Xbox/xemu

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ConfigFile = Join-Path $ScriptDir "xbdm_config.ini"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  xbdm_gdb_bridge Setup Wizard" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Check WSL
Write-Host "[1/4] Checking for WSL..." -ForegroundColor Yellow
try {
    $wslCheck = wsl --status 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "WSL not properly configured"
    }
    Write-Host "      WSL is installed" -ForegroundColor Green
} catch {
    Write-Host "      ERROR: WSL is not installed or not configured" -ForegroundColor Red
    Write-Host ""
    Write-Host "      To install WSL, run this command as Administrator:" -ForegroundColor Yellow
    Write-Host "      wsl --install" -ForegroundColor White
    Write-Host ""
    Write-Host "      Then restart your computer and run this setup again." -ForegroundColor Yellow
    exit 1
}

# Check for a WSL distro
Write-Host "[2/4] Checking for WSL distro..." -ForegroundColor Yellow
$distros = wsl --list --quiet 2>&1
if ([string]::IsNullOrWhiteSpace($distros) -or $distros -match "no installed distributions") {
    Write-Host "      ERROR: No WSL distribution installed" -ForegroundColor Red
    Write-Host ""
    Write-Host "      Install Ubuntu with:" -ForegroundColor Yellow
    Write-Host "      wsl --install -d Ubuntu" -ForegroundColor White
    exit 1
}
Write-Host "      WSL distro found" -ForegroundColor Green

# Step 2: Get Xbox/xemu IP
Write-Host "[3/4] Configure Xbox/xemu connection" -ForegroundColor Yellow
Write-Host ""

# Check for existing config
$existingIP = ""
if (Test-Path $ConfigFile) {
    $content = Get-Content $ConfigFile -Raw
    if ($content -match "xbox_ip\s*=\s*([^\r\n]+)") {
        $existingIP = $Matches[1].Trim()
    }
}

if ($existingIP) {
    Write-Host "      Current IP: $existingIP" -ForegroundColor Cyan
    $useExisting = Read-Host "      Keep this IP? (Y/n)"
    if ($useExisting -eq "" -or $useExisting -match "^[Yy]") {
        $xboxIP = $existingIP
    } else {
        $xboxIP = Read-Host "      Enter Xbox/xemu IP address"
    }
} else {
    Write-Host "      Enter the IP address of your Xbox or xemu instance."
    Write-Host "      (Find this in xemu: check the Xbox dashboard network settings)"
    Write-Host ""
    $xboxIP = Read-Host "      Xbox/xemu IP address"
}

# Validate IP format
if (-not ($xboxIP -match "^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$")) {
    Write-Host "      ERROR: Invalid IP address format" -ForegroundColor Red
    exit 1
}

# Step 3: Test connection
Write-Host ""
Write-Host "[4/4] Testing connection to $xboxIP..." -ForegroundColor Yellow

# Test ping via WSL
Write-Host "      Pinging $xboxIP..." -ForegroundColor Gray
$pingResult = wsl ping -c 2 -W 2 $xboxIP 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "      Ping successful" -ForegroundColor Green
} else {
    Write-Host "      WARNING: Ping failed (this might be OK if ICMP is blocked)" -ForegroundColor Yellow
}

# Test XBDM port
Write-Host "      Testing XBDM port 731..." -ForegroundColor Gray
$portTest = wsl bash -c "timeout 3 bash -c 'echo > /dev/tcp/$xboxIP/731' 2>&1 && echo SUCCESS || echo FAILED"
if ($portTest -match "SUCCESS") {
    Write-Host "      XBDM port 731 is open" -ForegroundColor Green
    $connectionOK = $true
} else {
    Write-Host "      WARNING: Could not connect to XBDM port 731" -ForegroundColor Yellow
    Write-Host "      Make sure xemu is running with debug BIOS" -ForegroundColor Yellow
    $connectionOK = $false
}

# Save config
Write-Host ""
Write-Host "Saving configuration..." -ForegroundColor Yellow

$configContent = @"
# xbdm_gdb_bridge Configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

[connection]
xbox_ip = $xboxIP
xbdm_port = 731

[gdb]
default_port = 1999

[options]
verbosity = 0
"@

$configContent | Out-File -FilePath $ConfigFile -Encoding UTF8
Write-Host "Configuration saved to: xbdm_config.ini" -ForegroundColor Green

# Final message
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
if ($connectionOK) {
    Write-Host "  Setup Complete!" -ForegroundColor Green
} else {
    Write-Host "  Setup Complete (with warnings)" -ForegroundColor Yellow
}
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "To connect to your Xbox/xemu:" -ForegroundColor White
Write-Host ""
Write-Host "  Option 1: Double-click xbdm.bat" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Option 2: From WSL terminal:" -ForegroundColor Cyan
Write-Host "            cd $(($ScriptDir -replace '\\','/') -replace 'C:','/mnt/c')" -ForegroundColor Gray
Write-Host "            ./xbdm" -ForegroundColor Gray
Write-Host ""
Write-Host "  Option 3: Run a single command:" -ForegroundColor Cyan
Write-Host "            ./xbdm -- dmversion" -ForegroundColor Gray
Write-Host ""

if (-not $connectionOK) {
    Write-Host "NOTE: Connection test failed. Before connecting, make sure:" -ForegroundColor Yellow
    Write-Host "  1. xemu is running" -ForegroundColor Yellow
    Write-Host "  2. xemu is using a debug BIOS (loads XBDM automatically)" -ForegroundColor Yellow
    Write-Host "  3. xemu network is set to 'Bridged Adapter'" -ForegroundColor Yellow
    Write-Host "  4. The IP address ($xboxIP) is correct" -ForegroundColor Yellow
    Write-Host ""
}

Write-Host "For help, see GETTING_STARTED.md" -ForegroundColor Gray
Write-Host ""
